# Generated by Django 4.1.1 on 2022-12-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_myuser_power_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="power_id",
            field=models.CharField(default=None, max_length=256, verbose_name="权限id"),
        ),
    ]
