# Generated by Django 4.1.1 on 2022-12-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_myuser_power_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("power", models.CharField(max_length=256, verbose_name="权限列表")),
            ],
            options={"db_table": "powerList",},
        ),
    ]
