# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\"\xa2\x02\n\x0cSearchParams\x1a\x89\x01\n\x06Params\x12\x12\n\nsearchType\x18\x01 \x01(\t\x12\x12\n\nsearchWord\x18\x02 \x01(\t\x12\x13\n\x0b\x63urrentPage\x18\x03 \x01(\x05\x12\x10\n\x08pageSize\x18\x04 \x01(\x05\x12\x30\n\x0csearchFilter\x18\x06 \x03(\x0e\x32\x1a.SearchParams.SearchFilter\x1a]\n\rSearchRequest\x12$\n\x06params\x18\x01 \x01(\x0b\x32\x14.SearchParams.Params\x12&\n\x07params1\x18\x02 \x01(\x0e\x32\x15.SearchParams.Params1\"\x15\n\x0cSearchFilter\x12\x05\n\x01\x61\x10\x00\"\x10\n\x07Params1\x12\x05\n\x01\x62\x10\x00\x62\x06proto3')



_SEARCHPARAMS = DESCRIPTOR.message_types_by_name['SearchParams']
_SEARCHPARAMS_PARAMS = _SEARCHPARAMS.nested_types_by_name['Params']
_SEARCHPARAMS_SEARCHREQUEST = _SEARCHPARAMS.nested_types_by_name['SearchRequest']
_SEARCHPARAMS_SEARCHFILTER = _SEARCHPARAMS.enum_types_by_name['SearchFilter']
_SEARCHPARAMS_PARAMS1 = _SEARCHPARAMS.enum_types_by_name['Params1']
SearchParams = _reflection.GeneratedProtocolMessageType('SearchParams', (_message.Message,), {

  'Params' : _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
    'DESCRIPTOR' : _SEARCHPARAMS_PARAMS,
    '__module__' : 'demo_pb2'
    # @@protoc_insertion_point(class_scope:SearchParams.Params)
    })
  ,

  'SearchRequest' : _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
    'DESCRIPTOR' : _SEARCHPARAMS_SEARCHREQUEST,
    '__module__' : 'demo_pb2'
    # @@protoc_insertion_point(class_scope:SearchParams.SearchRequest)
    })
  ,
  'DESCRIPTOR' : _SEARCHPARAMS,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:SearchParams)
  })
_sym_db.RegisterMessage(SearchParams)
_sym_db.RegisterMessage(SearchParams.Params)
_sym_db.RegisterMessage(SearchParams.SearchRequest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEARCHPARAMS._serialized_start=15
  _SEARCHPARAMS._serialized_end=305
  _SEARCHPARAMS_PARAMS._serialized_start=32
  _SEARCHPARAMS_PARAMS._serialized_end=169
  _SEARCHPARAMS_SEARCHREQUEST._serialized_start=171
  _SEARCHPARAMS_SEARCHREQUEST._serialized_end=264
  _SEARCHPARAMS_SEARCHFILTER._serialized_start=266
  _SEARCHPARAMS_SEARCHFILTER._serialized_end=287
  _SEARCHPARAMS_PARAMS1._serialized_start=289
  _SEARCHPARAMS_PARAMS1._serialized_end=305
# @@protoc_insertion_point(module_scope)
